#:schema node_modules/wrangler/config-schema.json

name = "gif-meme"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Production route
routes = [
  { pattern = "gifmeme.org/*", zone_name = "gifmeme.org" }
]

[[d1_databases]]
binding = "main-db"
database_name = "gifmeme-db"
database_id = "ca0e6dd0-8b5b-40c3-985a-08110ed426bd"

[[kv_namespaces]]
binding = "cache"
id = "7639311b729943dcb6d3a6cff8bcabea"

# Uncomment after enabling Analytics Engine in Cloudflare Dashboard:
# https://dash.cloudflare.com/639eb17ede2412f9933614707f8ed805/workers/analytics-engine
# [[analytics_engine_datasets]]
# binding = "gifmeme-analytics"
